### ISSUE TITLE
iptablesHasCheckCommand wrong version check when iptables version is v1.4.21

### ISSUE THREAD

**Issue by oonexdl** [coreos/go-iptables#123]
error msg: "running [/usr/sbin/iptables -t filter -C FORWARD -P FORWARD DROP --wait]: exit status 2: iptables v1.4.21: Cannot use -P with -C\n\nTry `iptables -h' or 'iptables --help' for more information.\n"

**Comment by dandare100** [comment]
I am not sure what you mean by wrong version check.

The version check looks good

![image](https://github.com/coreos/go-iptables/assets/5639208/8cb12fc1-396a-493b-a88a-1696091a161c)


The command itself  ("/usr/sbin/iptables -t filter -C FORWARD -P FORWARD DROP --wait") is invalid because it is trying to set a policy and check if a rule exists in a chain at the same time.

**Comment by oonexdl** [comment]
my fault, wrong rulespec were used when test
